#YAML 1.0
# Driftcam simulator: configuration file

# File containing density vs depth data, already interpolated at 1m interval.
# This will be used as a lookup table for a faster simulation, instead of recurrent interpolation at simulation time
density_profile: "data/ctd/interpolated/5K_ctd_average.csv"

input:
  start_depth: 5.0 # [m] initial depth 
  start_velocity: 0.0 # [m/s] initial vertical velocity
  eta:  0.02       # Value from D1-1 base design

  horizontal_speed: 2.5 # [cm/s] horizontal speed, for profile simulation

  seawater_density: 1024.0  # for those fixed density simulation cases [kg/m3]

  # Other simulation parameters 
  time_step: 0.1      # [s] Euler solver time step. Ideal step values: 0.1 , as smaller steps doesn't provide any noticeable change in system dynamics response
  min_dispensing_time: 1  # [s] minimum admissible time between drop ball event

  # variables you don't want to change unless you know what you're doing
  # define constants andd platform dimensions
  gravity: 9.81           # [m/s2]
  drag_coefficient: 1.2   # Geometry defined 
  radius: 0.2             # [m] transversal section
  tau : 7                 # [m] system dynamic response constant
  simulation_time: 6500   # [s] total simulation time

  # Using parameters from Al6061T housing
  main_mass: 27.40        # [kg] mass of the main body
  main_volume: 0.0196      # [m3] volume of the main body

  ball_diameter: 0.014    # [m] ballast unit diameter
  ball_density: 7800      # [kg/m3] 

  ballast_mass: 1.624   # [kg] total ballast mass: ws + wd

  flotation_mass: 5.115    # [kg]
  flotation_density: 400.0 # [kg/m3]

control:
  mission_duration: 2000 # [s] time in control mode before triggering surfacing mode
  floor_profundity: 300   # [m] fixed simulation profundity
  braking_altitude: 25    # [m] altitude threshold: depth control will be triggered when. depth > floor_profundity - target_altitude
  target_altitude: 2      # [m] altitude threshold: depth control will be triggered when. depth > floor_profundity - target_altitude
                          # it is equivalent to say when: altitude < target_altitude

output:
  file_preffix: "sim"
  file_extension: ".csv"
  file_path: "data/simulations/"